A collection of Python tools for working with FAOSTAT and other data related to global development, economic history and agriculture.  

I am a novice learning as I go, so this is more like a personal sandbox then a reliable repository.
* datapeek
Functions for having a look at what's in a Pandas dataframe.
* faocodes 
Looks up [[http://faostat3.fao.org/][FAOSTAT]] numerical codes for countries or commodities, and vice versa, via command line. It uses a `members.json` file downloaded from  [[http://data.fao.org/developers/api/v1/en/resources/members.json?pageSize=1000&fields=mnemonic%2Clabel%40en%2Cproperties.*][this link]], and also works as a library. I eventually hope to use it to request data via API with Quandl.
* faoplot 
Will automatically generate plots from FAOSTAT data, based on lists of items, element and country codes. Uses `faocodes` as a library. 
* oldmoney
Will use the [[https://github.com/hgrecco/pint][Pint]] library to work with data given in [[http://en.wikipedia.org/wiki/%C2%A3sd][pre-decimal British pounds]] (e.g. £2 3s 6d). 
